star_do/config/routes.rb
Rails.application.routes.draw do
  resources :items
  resources :bundles
  resources :rooms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

star_do/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

star_do/app/models/bundle.rb
class Bundle < ApplicationRecord
    belongs_to :room
    has_many :items
end

star_do/app/models/item.rb
class Item < ApplicationRecord
    belongs_to :bundle
end

star_do/app/models/room.rb
class Room < ApplicationRecord
    has_many :bundles
end

star_do/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

star_do/app/controllers/bundles_controller.rb
class BundlesController < ApplicationController
  before_action :set_bundle, only: [:show, :edit, :update, :destroy]

  # GET /bundles
  # GET /bundles.json
  def index
    @bundles = Bundle.all
  end

  # GET /bundles/1
  # GET /bundles/1.json
  def show
  end

  # GET /bundles/new
  def new
    @bundle = Bundle.new
  end

  # GET /bundles/1/edit
  def edit
  end

  # POST /bundles
  # POST /bundles.json
  def create
    @bundle = Bundle.new(bundle_params)

    respond_to do |format|
      if @bundle.save
        format.html { redirect_to @bundle, notice: 'Bundle was successfully created.' }
        format.json { render :show, status: :created, location: @bundle }
      else
        format.html { render :new }
        format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bundles/1
  # PATCH/PUT /bundles/1.json
  def update
    respond_to do |format|
      if @bundle.update(bundle_params)
        format.html { redirect_to @bundle, notice: 'Bundle was successfully updated.' }
        format.json { render :show, status: :ok, location: @bundle }
      else
        format.html { render :edit }
        format.json { render json: @bundle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bundles/1
  # DELETE /bundles/1.json
  def destroy
    @bundle.destroy
    respond_to do |format|
      format.html { redirect_to bundles_url, notice: 'Bundle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bundle
      @bundle = Bundle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bundle_params
      params.require(:bundle).permit(:name, :reward, :room_id)
    end
end

star_do/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:name, :type, :purchase, :location, :time, :weather, :season, :quantity, :note, :bundle_id)
    end
end

star_do/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :reward)
    end
end

star_do/app/helpers/application_helper.rb
module ApplicationHelper
end

star_do/app/helpers/bundles_helper.rb
module BundlesHelper
end

star_do/app/helpers/items_helper.rb
module ItemsHelper
end

star_do/app/helpers/rooms_helper.rb
module RoomsHelper
end

star_do/app/views/bundles/_form.html.erb
<%= form_with(model: bundle, local: true) do |form| %>
  <% if bundle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bundle.errors.count, "error") %> prohibited this bundle from being saved:</h2>

      <ul>
        <% bundle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :reward %>
    <%= form.text_field :reward %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.number_field :room_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

star_do/app/views/bundles/edit.html.erb
<h1>Editing Bundle</h1>

<%= render 'form', bundle: @bundle %>

<%= link_to 'Show', @bundle %> |
<%= link_to 'Back', bundles_path %>

star_do/app/views/bundles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bundles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Reward</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bundles.each do |bundle| %>
      <tr>
        <td><%= bundle.name %></td>
        <td><%= bundle.reward %></td>
        <td><%= bundle.room_id %></td>
        <td><%= link_to 'Show', bundle %></td>
        <td><%= link_to 'Edit', edit_bundle_path(bundle) %></td>
        <td><%= link_to 'Destroy', bundle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bundle', new_bundle_path %>

star_do/app/views/bundles/new.html.erb
<h1>New Bundle</h1>

<%= render 'form', bundle: @bundle %>

<%= link_to 'Back', bundles_path %>

star_do/app/views/bundles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bundle.name %>
</p>

<p>
  <strong>Reward:</strong>
  <%= @bundle.reward %>
</p>

<p>
  <strong>Room:</strong>
  <%= @bundle.room_id %>
</p>

<%= link_to 'Edit', edit_bundle_path(@bundle) %> |
<%= link_to 'Back', bundles_path %>

star_do/app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :purchase %>
    <%= form.check_box :purchase %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="field">
    <%= form.label :bundle_id %>
    <%= form.text_field :bundle_id %>
  </div>

  <div class="field">
    <%= form.label :quality %>
    <%= form.text_field :quality %>
  </div>

  <div class="field">
    <%= form.label :farm %>
    <%= form.check_box :farm %>
  </div>

  <div class="field">
    <%= form.label :forage %>
    <%= form.check_box :forage %>
  </div>

  <div class="field">
    <%= form.label :fish %>
    <%= form.check_box :fish %>
  </div>

  <div class="field">
    <%= form.label :artisan %>
    <%= form.check_box :artisan %>
  </div>

  <div class="field">
    <%= form.label :mine %>
    <%= form.check_box :mine %>
  </div>

  <div class="field">
    <%= form.label :monster %>
    <%= form.check_box :monster %>
  </div>

  <div class="field">
    <%= form.label :crab_pot %>
    <%= form.check_box :crab_pot %>
  </div>

  <div class="field">
    <%= form.label :misc %>
    <%= form.check_box :misc %>
  </div>

  <div class="field">
    <%= form.label :spring %>
    <%= form.check_box :spring %>
  </div>

  <div class="field">
    <%= form.label :summer %>
    <%= form.check_box :summer %>
  </div>

  <div class="field">
    <%= form.label :fall %>
    <%= form.check_box :fall %>
  </div>

  <div class="field">
    <%= form.label :winter %>
    <%= form.check_box :winter %>
  </div>

  <div class="field">
    <%= form.label :morning %>
    <%= form.check_box :morning %>
  </div>

  <div class="field">
    <%= form.label :noon %>
    <%= form.check_box :noon %>
  </div>

  <div class="field">
    <%= form.label :afternoon %>
    <%= form.check_box :afternoon %>
  </div>

  <div class="field">
    <%= form.label :night %>
    <%= form.check_box :night %>
  </div>

  <div class="field">
    <%= form.label :location_river_town %>
    <%= form.check_box :location_river_town %>
  </div>

  <div class="field">
    <%= form.label :location_river_forest %>
    <%= form.check_box :location_river_forest %>
  </div>

  <div class="field">
    <%= form.label :location_mountain_lake %>
    <%= form.check_box :location_mountain_lake %>
  </div>

  <div class="field">
    <%= form.label :location_mines %>
    <%= form.check_box :location_mines %>
  </div>

  <div class="field">
    <%= form.label :location_secret_woods %>
    <%= form.check_box :location_secret_woods %>
  </div>

  <div class="field">
    <%= form.label :location_cindersap_forest %>
    <%= form.check_box :location_cindersap_forest %>
  </div>

  <div class="field">
    <%= form.label :location_bus_stop %>
    <%= form.check_box :location_bus_stop %>
  </div>

  <div class="field">
    <%= form.label :location_beach %>
    <%= form.check_box :location_beach %>
  </div>

  <div class="field">
    <%= form.label :location_mountain %>
    <%= form.check_box :location_mountain %>
  </div>

  <div class="field">
    <%= form.label :location_railroad %>
    <%= form.check_box :location_railroad %>
  </div>

  <div class="field">
    <%= form.label :location_quarry %>
    <%= form.check_box :location_quarry %>
  </div>

  <div class="field">
    <%= form.label :location_farm %>
    <%= form.check_box :location_farm %>
  </div>

  <div class="field">
    <%= form.label :location_forest_pond %>
    <%= form.check_box :location_forest_pond %>
  </div>

  <div class="field">
    <%= form.label :location_witchs_swamp %>
    <%= form.check_box :location_witchs_swamp %>
  </div>

  <div class="field">
    <%= form.label :location_desert %>
    <%= form.check_box :location_desert %>
  </div>

  <div class="field">
    <%= form.label :sun %>
    <%= form.check_box :sun %>
  </div>

  <div class="field">
    <%= form.label :rain %>
    <%= form.check_box :rain %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

star_do/app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

star_do/app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Purchase</th>
      <th>Quantity</th>
      <th>Note</th>
      <th>Bundle</th>
      <th>Quality</th>
      <th>Farm</th>
      <th>Forage</th>
      <th>Fish</th>
      <th>Artisan</th>
      <th>Mine</th>
      <th>Monster</th>
      <th>Crab pot</th>
      <th>Misc</th>
      <th>Spring</th>
      <th>Summer</th>
      <th>Fall</th>
      <th>Winter</th>
      <th>Morning</th>
      <th>Noon</th>
      <th>Afternoon</th>
      <th>Night</th>
      <th>Location river town</th>
      <th>Location river forest</th>
      <th>Location mountain lake</th>
      <th>Location mines</th>
      <th>Location secret woods</th>
      <th>Location cindersap forest</th>
      <th>Location bus stop</th>
      <th>Location beach</th>
      <th>Location mountain</th>
      <th>Location railroad</th>
      <th>Location quarry</th>
      <th>Location farm</th>
      <th>Location forest pond</th>
      <th>Location witchs swamp</th>
      <th>Location desert</th>
      <th>Sun</th>
      <th>Rain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.purchase %></td>
        <td><%= item.quantity %></td>
        <td><%= item.note %></td>
        <td><%= item.bundle_id %></td>
        <td><%= item.quality %></td>
        <td><%= item.farm %></td>
        <td><%= item.forage %></td>
        <td><%= item.fish %></td>
        <td><%= item.artisan %></td>
        <td><%= item.mine %></td>
        <td><%= item.monster %></td>
        <td><%= item.crab_pot %></td>
        <td><%= item.misc %></td>
        <td><%= item.spring %></td>
        <td><%= item.summer %></td>
        <td><%= item.fall %></td>
        <td><%= item.winter %></td>
        <td><%= item.morning %></td>
        <td><%= item.noon %></td>
        <td><%= item.afternoon %></td>
        <td><%= item.night %></td>
        <td><%= item.location_river_town %></td>
        <td><%= item.location_river_forest %></td>
        <td><%= item.location_mountain_lake %></td>
        <td><%= item.location_mines %></td>
        <td><%= item.location_secret_woods %></td>
        <td><%= item.location_cindersap_forest %></td>
        <td><%= item.location_bus_stop %></td>
        <td><%= item.location_beach %></td>
        <td><%= item.location_mountain %></td>
        <td><%= item.location_railroad %></td>
        <td><%= item.location_quarry %></td>
        <td><%= item.location_farm %></td>
        <td><%= item.location_forest_pond %></td>
        <td><%= item.location_witchs_swamp %></td>
        <td><%= item.location_desert %></td>
        <td><%= item.sun %></td>
        <td><%= item.rain %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

star_do/app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

star_do/app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Purchase:</strong>
  <%= @item.purchase %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Note:</strong>
  <%= @item.note %>
</p>

<p>
  <strong>Bundle:</strong>
  <%= @item.bundle_id %>
</p>

<p>
  <strong>Quality:</strong>
  <%= @item.quality %>
</p>

<p>
  <strong>Farm:</strong>
  <%= @item.farm %>
</p>

<p>
  <strong>Forage:</strong>
  <%= @item.forage %>
</p>

<p>
  <strong>Fish:</strong>
  <%= @item.fish %>
</p>

<p>
  <strong>Artisan:</strong>
  <%= @item.artisan %>
</p>

<p>
  <strong>Mine:</strong>
  <%= @item.mine %>
</p>

<p>
  <strong>Monster:</strong>
  <%= @item.monster %>
</p>

<p>
  <strong>Crab pot:</strong>
  <%= @item.crab_pot %>
</p>

<p>
  <strong>Misc:</strong>
  <%= @item.misc %>
</p>

<p>
  <strong>Spring:</strong>
  <%= @item.spring %>
</p>

<p>
  <strong>Summer:</strong>
  <%= @item.summer %>
</p>

<p>
  <strong>Fall:</strong>
  <%= @item.fall %>
</p>

<p>
  <strong>Winter:</strong>
  <%= @item.winter %>
</p>

<p>
  <strong>Morning:</strong>
  <%= @item.morning %>
</p>

<p>
  <strong>Noon:</strong>
  <%= @item.noon %>
</p>

<p>
  <strong>Afternoon:</strong>
  <%= @item.afternoon %>
</p>

<p>
  <strong>Night:</strong>
  <%= @item.night %>
</p>

<p>
  <strong>Location river town:</strong>
  <%= @item.location_river_town %>
</p>

<p>
  <strong>Location river forest:</strong>
  <%= @item.location_river_forest %>
</p>

<p>
  <strong>Location mountain lake:</strong>
  <%= @item.location_mountain_lake %>
</p>

<p>
  <strong>Location mines:</strong>
  <%= @item.location_mines %>
</p>

<p>
  <strong>Location secret woods:</strong>
  <%= @item.location_secret_woods %>
</p>

<p>
  <strong>Location cindersap forest:</strong>
  <%= @item.location_cindersap_forest %>
</p>

<p>
  <strong>Location bus stop:</strong>
  <%= @item.location_bus_stop %>
</p>

<p>
  <strong>Location beach:</strong>
  <%= @item.location_beach %>
</p>

<p>
  <strong>Location mountain:</strong>
  <%= @item.location_mountain %>
</p>

<p>
  <strong>Location railroad:</strong>
  <%= @item.location_railroad %>
</p>

<p>
  <strong>Location quarry:</strong>
  <%= @item.location_quarry %>
</p>

<p>
  <strong>Location farm:</strong>
  <%= @item.location_farm %>
</p>

<p>
  <strong>Location forest pond:</strong>
  <%= @item.location_forest_pond %>
</p>

<p>
  <strong>Location witchs swamp:</strong>
  <%= @item.location_witchs_swamp %>
</p>

<p>
  <strong>Location desert:</strong>
  <%= @item.location_desert %>
</p>

<p>
  <strong>Sun:</strong>
  <%= @item.sun %>
</p>

<p>
  <strong>Rain:</strong>
  <%= @item.rain %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

star_do/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

star_do/app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :reward %>
    <%= form.text_field :reward %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

star_do/app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

star_do/app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Reward</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.reward %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

star_do/app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

star_do/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Reward:</strong>
  <%= @room.reward %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>